/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UploadCiFindingRequest } from '../../models/upload-ci-finding-request';
import { UploadCiFindingResponse } from '../../models/upload-ci-finding-response';

export interface UploadCiFinding$Params {
      body?: UploadCiFindingRequest
}

export function uploadCiFinding(http: HttpClient, rootUrl: string, params?: UploadCiFinding$Params, context?: HttpContext): Observable<StrictHttpResponse<UploadCiFindingResponse>> {
  const rb = new RequestBuilder(rootUrl, uploadCiFinding.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UploadCiFindingResponse>;
    })
  );
}

uploadCiFinding.PATH = '/api/ci/finding';
