site_name: Techanv Warden
site_url: https://sussec.github.io/warden
site_author: Duo
site_description: >-
  Techanv Warden
repo_name: Techanv Warden
repo_url: https://github.com/sussec/warden
edit_uri: "blob/main/docs/"
copyright: Copyright &copy; 2026 Techanv Consulting

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.action.edit
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  highlightjs: true
  hljs_languages:
    - yaml
  font:
    text: Inter

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details

nav:
  - Getting Started:
    - Installation: installation.md
    - System Setting:
      - General: setting/general.md
      - Access Token: setting/ci-token.md
      - Integration: setting/integration.md
    - Security Integration:
      - security-integration/index.md
      - Environment Variables: security-integration/environment-variables.md
      - Static Application Security Testing (SAST):
        - Semgrep: security-integration/sast/semgrep.md
        - Gitleaks: security-integration/sast/gitleaks.md
      - Software Composition Analysis (SCA):
        - Trivy: security-integration/sca/trivy.md
