/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RedmineMetadata } from '../../models/redmine-metadata';
import { RedmineSetting } from '../../models/redmine-setting';

export interface GetRedmineMetadataIntegration$Params {
  reload?: boolean;
      body?: RedmineSetting
}

export function getRedmineMetadataIntegration(http: HttpClient, rootUrl: string, params?: GetRedmineMetadataIntegration$Params, context?: HttpContext): Observable<StrictHttpResponse<RedmineMetadata>> {
  const rb = new RequestBuilder(rootUrl, getRedmineMetadataIntegration.PATH, 'post');
  if (params) {
    rb.query('reload', params.reload, {"style":"form"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RedmineMetadata>;
    })
  );
}

getRedmineMetadataIntegration.PATH = '/api/integration/redmine/metadata';
