/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PackageInfo } from '../../models/package-info';

export interface ListPackageDependency$Params {
  packageId: string;
}

export function listPackageDependency(http: HttpClient, rootUrl: string, params: ListPackageDependency$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PackageInfo>>> {
  const rb = new RequestBuilder(rootUrl, listPackageDependency.PATH, 'get');
  if (params) {
    rb.path('packageId', params.packageId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PackageInfo>>;
    })
  );
}

listPackageDependency.PATH = '/api/package/{packageId}/dependencies';
