{{- if .Values.osv.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warden.osvServiceName" . }}
  labels:
    {{- include "warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: osv
spec:
  type: {{ .Values.osv.service.type }}
  ports:
    - name: http
      port: {{ .Values.osv.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "warden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: osv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "warden.fullname" . }}-osv
  labels:
    {{- include "warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: osv
spec:
  {{- if not .Values.osv.autoscaling.enabled }}
  replicas: {{ .Values.osv.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.osv.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "warden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: osv
  template:
    metadata:
      labels:
        {{- include "warden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: osv
    spec:
      serviceAccountName: {{ include "warden.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.osv.podSecurityContext | nindent 8 }}
      containers:
        - name: osv
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.global.imageProject }}/{{ .Values.osv.image.repository }}:{{ .Values.osv.image.tag }}"
          imagePullPolicy: {{ .Values.osv.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.osv.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: OSV_URL
              value: {{ .Values.osv.env.osvUrl | quote }}
            - name: CACHE_TTL
              value: {{ .Values.osv.env.cacheTtl | quote }}
          livenessProbe:
            {{- toYaml .Values.osv.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.osv.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.osv.resources | nindent 12 }}
      {{- with .Values.osv.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $affinity := .Values.osv.affinity }}
      {{- if or $affinity .Values.osv.podAntiAffinity }}
      affinity:
        {{- with $affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.osv.podAntiAffinity }}
        {{- include "warden.podAntiAffinity" (dict "root" . "component" "osv" "mode" .Values.osv.podAntiAffinity) | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.osv.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
