/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthConfig {
  disablePasswordLogon?: boolean;
  openIdConnectEnable?: boolean;
  openIdConnectProvider?: string | null;
}
