/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangedFileStatus } from '../models/changed-file-status';
export interface ChangedFile {
  from?: string | null;
  status?: ChangedFileStatus;
  to?: string | null;
}
