/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingLocation } from '../models/finding-location';
import { FindingMetadata } from '../models/finding-metadata';
import { FindingSeverity } from '../models/finding-severity';
export interface CiFinding {
  category?: string | null;
  description: string;
  fixDeadline?: string | null;
  id?: string | null;
  identity: string;
  location?: FindingLocation;
  metadata?: FindingMetadata;
  name: string;
  recommendation?: string | null;
  ruleId?: string | null;
  severity: FindingSeverity;
}
