/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CiPackage {
  group?: string | null;
  id?: string | null;
  license?: string | null;
  location?: string | null;
  name?: string | null;
  pkgId?: string | null;
  type?: string | null;
  version?: string | null;
}
