/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VulnerabilityInfo } from '../models/vulnerability-info';
export interface CiPackageInfo {
  group?: string | null;
  license?: string | null;
  location?: string | null;
  name?: string | null;
  pkgId?: string | null;
  type?: string | null;
  version?: string | null;
  vulnerabilities?: Array<VulnerabilityInfo> | null;
}
