/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CiScanInfo {
  lastCommitSha?: string | null;
  scanId?: string;
  scanUrl?: string | null;
}
