/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CiTokens {
  createdAt?: string;
  expiredAt?: string | null;
  id?: string;
  name?: string | null;
  updatedAt?: string | null;
  value?: string | null;
}
