/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FindingSortField {
  Severity = 'Severity',
  Status = 'Status',
  CreatedAt = 'CreatedAt',
  UpdatedAt = 'UpdatedAt',
  Name = 'Name'
}
