/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FindingStatus {
  Open = 'Open',
  Confirmed = 'Confirmed',
  AcceptedRisk = 'AcceptedRisk',
  Fixed = 'Fixed',
  Incorrect = 'Incorrect'
}
