/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindingLocation {
  endColumn?: number | null;
  endLine?: number | null;
  path?: string | null;
  snippet?: string | null;
  startColumn?: number | null;
  startLine?: number | null;
}
