/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommitType } from '../models/commit-type';
import { FindingStatus } from '../models/finding-status';
export interface FindingScan {
  action?: CommitType;
  branch?: string | null;
  commitHash?: string | null;
  isDefault?: boolean;
  scanId?: string;
  status?: FindingStatus;
  targetBranch?: string | null;
}
