/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingActivity } from '../models/finding-activity';
export interface FindingActivityPage {
  count?: number;
  currentPage?: number;
  items?: Array<FindingActivity> | null;
  pageCount?: number;
  size?: number;
}
