/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSeverity } from '../models/finding-severity';
import { FindingSortField } from '../models/finding-sort-field';
import { FindingStatus } from '../models/finding-status';
export interface FindingFilter {
  category?: string | null;
  commitId?: string | null;
  desc?: boolean;
  endCreatedAt?: string | null;
  endFixedAt?: string | null;
  name?: string | null;
  page?: number;
  projectId?: string | null;
  projectManagerId?: string | null;
  ruleId?: string | null;
  scanner?: Array<string> | null;
  severity?: Array<FindingSeverity> | null;
  size?: number;
  sortBy?: FindingSortField;
  sourceControlId?: string | null;
  startCreatedAt?: string | null;
  startFixedAt?: string | null;
  status?: Array<FindingStatus> | null;
}
