/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum FindingActivityType {
  Open = 'Open',
  Fixed = 'Fixed',
  Reopen = 'Reopen',
  Comment = 'Comment',
  ChangeStatus = 'ChangeStatus',
  ChangeDeadline = 'ChangeDeadline',
  ChangeSeverity = 'ChangeSeverity'
}
