/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingLocation } from '../models/finding-location';
export interface FindingMetadata {
  cvss?: string | null;
  cvssScore?: string | null;
  cwes?: Array<string> | null;
  findingFlow?: Array<FindingLocation> | null;
  references?: Array<string> | null;
}
