/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SourceType } from '../models/source-type';
export interface FindingProject {
  id?: string;
  name?: string | null;
  repoId?: string | null;
  repoUrl?: string | null;
  sourceType?: SourceType;
}
