/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingLocation } from '../models/finding-location';
import { FindingMetadata } from '../models/finding-metadata';
import { FindingProject } from '../models/finding-project';
import { FindingScan } from '../models/finding-scan';
import { FindingSeverity } from '../models/finding-severity';
import { FindingStatus } from '../models/finding-status';
import { ScannerType } from '../models/scanner-type';
import { Tickets } from '../models/tickets';
export interface FindingDetail {
  description?: string | null;
  fixDeadline?: string | null;
  id?: string;
  identity?: string | null;
  location?: FindingLocation;
  metadata?: FindingMetadata;
  name?: string | null;
  project?: FindingProject;
  recommendation?: string | null;
  ruleId?: string | null;
  scanner?: string | null;
  scans?: Array<FindingScan> | null;
  severity?: FindingSeverity;
  status?: FindingStatus;
  ticket?: Tickets;
  type?: ScannerType;
}
