/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommitType } from '../models/commit-type';
import { Projects } from '../models/projects';
export interface GitCommits {
  branch?: string | null;
  commitHash?: string | null;
  commitTitle?: string | null;
  createdAt?: string;
  id?: string;
  isDefault?: boolean;
  mergeRequestId?: string | null;
  project?: Projects;
  projectId?: string;
  targetBranch?: string | null;
  type?: CommitType;
  updatedAt?: string | null;
}
