/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MailAlertSetting {
  active: boolean;
  fixedFindingEvent: boolean;
  needTriageFindingEvent: boolean;
  newFindingEvent: boolean;
  projectWithoutMemberEvent: boolean;
  receivers?: Array<string> | null;
  scanCompletedEvent: boolean;
  scanFailedEvent: boolean;
  securityAlertEvent: boolean;
}
