/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MailProjectAlertSetting {
  active: boolean;
  fixedFindingEvent: boolean;
  needTriageFindingEvent: boolean;
  newFindingEvent: boolean;
  scanCompletedEvent: boolean;
  scanFailedEvent: boolean;
  securityAlertEvent: boolean;
}
