/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OpenIdConnectSetting {
  authority?: string | null;
  clientId?: string | null;
  clientSecret?: string | null;
  displayName?: string | null;
  enable?: boolean;
  schemeOverride?: string | null;
}
