/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PackageInfo {
  dependencyCount?: number;
  group?: string | null;
  id?: string;
  isVulnerable?: boolean;
  name?: string | null;
  type?: string | null;
  version?: string | null;
}
