/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RiskImpact } from '../models/risk-impact';
import { RiskLevel } from '../models/risk-level';
export interface Packages {
  createdAt?: string;
  fixedVersion?: string | null;
  group?: string | null;
  id?: string;
  license?: string | null;
  name?: string | null;
  pkgId?: string | null;
  riskImpact?: RiskImpact;
  riskLevel?: RiskLevel;
  type?: string | null;
  updatedAt?: string | null;
  version?: string | null;
}
