/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Packages } from '../models/packages';
import { Vulnerabilities } from '../models/vulnerabilities';
export interface PackageDetail {
  dependencies?: Array<Packages> | null;
  info?: Packages;
  vulnerabilities?: Array<Vulnerabilities> | null;
}
