/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PackageStatus } from '../models/package-status';
import { ProjectPackageSortField } from '../models/project-package-sort-field';
import { RiskLevel } from '../models/risk-level';
export interface PackageFilter {
  desc?: boolean;
  name?: string | null;
  page?: number;
  severity?: Array<RiskLevel> | null;
  size?: number;
  sortBy?: ProjectPackageSortField;
  status?: PackageStatus;
}
