/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectRole } from '../models/project-role';
export interface ProjectMember {
  avatar?: string | null;
  createdAt?: string;
  email?: string | null;
  fullName?: string | null;
  role?: ProjectRole;
  userId?: string;
  userName?: string | null;
}
