/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectScan } from '../models/project-scan';
export interface ProjectScanPage {
  count?: number;
  currentPage?: number;
  items?: Array<ProjectScan> | null;
  pageCount?: number;
  size?: number;
}
