/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectSortField } from '../models/project-sort-field';
export interface ProjectFilter {
  desc?: boolean;
  memberUserId?: string | null;
  name?: string | null;
  page?: number;
  size?: number;
  sortBy?: ProjectSortField;
  sourceControlId?: string | null;
}
