/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommitType } from '../models/commit-type';
import { ProjectScanSummary } from '../models/project-scan-summary';
export interface ProjectCommitScanSummary {
  branch?: string | null;
  commitId?: string;
  isDefault?: boolean;
  scans?: Array<ProjectScanSummary> | null;
  targetBranch?: string | null;
  title?: string | null;
  type?: CommitType;
}
