/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScannerType } from '../models/scanner-type';
import { ScanStatus } from '../models/scan-status';
export interface ProjectScanFilter {
  desc?: boolean;
  page?: number;
  scanner?: string | null;
  size?: number;
  status?: ScanStatus;
  type?: ScannerType;
}
