/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BranchStatusPackage } from '../models/branch-status-package';
import { Packages } from '../models/packages';
import { PackageStatus } from '../models/package-status';
import { Tickets } from '../models/tickets';
import { Vulnerabilities } from '../models/vulnerabilities';
export interface ProjectPackageDetailResponse {
  branchStatus?: Array<BranchStatusPackage> | null;
  dependencies?: Array<Packages> | null;
  ignoreReason?: string | null;
  info?: Packages;
  location?: string | null;
  projectId?: string;
  projectName?: string | null;
  status?: PackageStatus;
  ticket?: Tickets;
  vulnerabilities?: Array<Vulnerabilities> | null;
}
