/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommitType } from '../models/commit-type';
export interface ProjectCommitSummary {
  branch?: string | null;
  commitId?: string;
  isDefault?: boolean;
  targetBranch?: string | null;
  type?: CommitType;
}
