/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectPackage } from '../models/project-package';
export interface ProjectPackagePage {
  count?: number;
  currentPage?: number;
  items?: Array<ProjectPackage> | null;
  pageCount?: number;
  size?: number;
}
