/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectRole } from '../models/project-role';
export interface ProjectMemberFilter {
  desc?: boolean;
  name?: string | null;
  page?: number;
  role?: ProjectRole;
  size?: number;
}
