/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectCommitScanSummary } from '../models/project-commit-scan-summary';
export interface ProjectCommitScanSummaryPage {
  count?: number;
  currentPage?: number;
  items?: Array<ProjectCommitScanSummary> | null;
  pageCount?: number;
  size?: number;
}
