/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScannerType } from '../models/scanner-type';
import { ScanStatus } from '../models/scan-status';
export interface ProjectScanSummary {
  completed?: string | null;
  confirmed?: number;
  critical?: number;
  fixed?: number;
  high?: number;
  ignored?: number;
  jobUrl?: string | null;
  low?: number;
  medium?: number;
  open?: number;
  scanner?: string | null;
  started?: string;
  status?: ScanStatus;
  type?: ScannerType;
}
