/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectCommitFilter {
  desc?: boolean;
  name?: string | null;
  page?: number;
  size?: number;
}
