/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RedmineSetting {
  active?: boolean;
  priorityId?: number;
  projectId?: number;
  statusId?: number;
  token?: string | null;
  trackerId?: number;
  url?: string | null;
}
