/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IdName } from '../models/id-name';
export interface RedmineMetadata {
  priorities?: Array<IdName> | null;
  projects?: Array<IdName> | null;
  statuses?: Array<IdName> | null;
  trackers?: Array<IdName> | null;
}
