/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RedmineProjectSetting {
  active?: boolean;
  priorityId?: number;
  projectId?: number;
  statusId?: number;
  trackerId?: number;
}
