/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RuleConfidence } from '../models/rule-confidence';
import { RuleStatus } from '../models/rule-status';
export interface RuleInfo {
  confidence?: RuleConfidence;
  correctFinding?: number;
  createdAt?: string;
  id?: string | null;
  incorrectFinding?: number;
  scannerId?: string;
  scannerName?: string | null;
  status?: RuleStatus;
  uncertainFinding?: number;
  updatedAt?: string | null;
}
