/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RuleInfo } from '../models/rule-info';
export interface RuleInfoPage {
  count?: number;
  currentPage?: number;
  items?: Array<RuleInfo> | null;
  pageCount?: number;
  size?: number;
}
