/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum RuleConfidence {
  High = 'High',
  Medium = 'Medium',
  Low = 'Low',
  Unknown = 'Unknown'
}
