/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SastStatus } from '../models/sast-status';
import { SeveritySeries } from '../models/severity-series';
import { TopFinding } from '../models/top-finding';
export interface SastStatistic {
  severity: SeveritySeries;
  status: SastStatus;
  topFindings: Array<TopFinding>;
}
