/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScaStatus } from '../models/sca-status';
import { SeveritySeries } from '../models/severity-series';
import { TopDependency } from '../models/top-dependency';
export interface ScaStatistic {
  severity: SeveritySeries;
  status: ScaStatus;
  topDependencies: Array<TopDependency>;
}
