/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScannerType } from '../models/scanner-type';
export interface Scanners {
  createdAt?: string;
  id?: string;
  name?: string | null;
  normalizedName?: string | null;
  type?: ScannerType;
  updatedAt?: string | null;
}
