/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ScannerType {
  Sast = 'Sast',
  Dast = 'Dast',
  Iast = 'Iast',
  Dependency = 'Dependency',
  Container = 'Container',
  Secret = 'Secret'
}
