/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScannerType } from '../models/scanner-type';
export interface ScannerFilter {
  name?: string | null;
  projectId?: string | null;
  type?: Array<ScannerType> | null;
}
