/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignInResponse {
  accessToken?: string | null;
  refreshToken?: string | null;
  requireConfirmEmail?: boolean | null;
  requireTwoFactor?: boolean | null;
}
