/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SmtpSetting {
  ignoreSsl?: boolean;
  name?: string | null;
  password?: string | null;
  port: number;
  server: string;
  useSsl?: boolean;
  userName: string;
}
