/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum SourceType {
  Local = 'Local',
  GitLab = 'GitLab',
  GitHub = 'GitHub',
  Bitbucket = 'Bitbucket'
}
