/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SourceType } from '../models/source-type';
export interface SourceControls {
  createdAt?: string;
  id?: string;
  normalizedUrl?: string | null;
  type?: SourceType;
  updatedAt?: string | null;
  url?: string | null;
}
