/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamsAlertSetting {
  active: boolean;
  fixedFindingEvent: boolean;
  needTriageFindingEvent: boolean;
  newFindingEvent: boolean;
  projectWithoutMemberEvent: boolean;
  scanCompletedEvent: boolean;
  scanFailedEvent: boolean;
  securityAlertEvent: boolean;
  webhook?: string | null;
}
