/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThresholdSetting } from '../models/threshold-setting';
export interface ThresholdProject {
  sast?: ThresholdSetting;
  sca?: ThresholdSetting;
}
