/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ThresholdMode {
  MonitorOnly = 'MonitorOnly',
  BlockOnConfirmation = 'BlockOnConfirmation',
  BlockOnDetection = 'BlockOnDetection'
}
