/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TopDependency {
  critical: number;
  group?: string | null;
  high: number;
  info: number;
  low: number;
  medium: number;
  name: string;
  version: string;
}
