/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserStatus } from '../models/user-status';
export interface UpdateUserRequest {
  email?: string | null;
  fullName?: string | null;
  role?: string | null;
  status?: UserStatus;
  verified?: boolean | null;
}
