/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScanStatus } from '../models/scan-status';
export interface UpdateCiScanRequest {
  description?: string | null;
  status?: ScanStatus;
}
