/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PackageStatus } from '../models/package-status';
export interface UpdateProjectPackageRequest {
  ignoreReason?: string | null;
  status?: PackageStatus;
}
