/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectRole } from '../models/project-role';
export interface UpdateProjectMemberRequest {
  role?: ProjectRole;
}
