/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChangedFile } from '../models/changed-file';
import { CiFinding } from '../models/ci-finding';
import { ScanStrategy } from '../models/scan-strategy';
export interface UploadCiFindingRequest {
  changedFiles?: Array<ChangedFile> | null;
  findings?: Array<CiFinding> | null;
  scanId: string;
  strategy?: ScanStrategy;
}
