/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CiPackage } from '../models/ci-package';
import { CiPackageDependency } from '../models/ci-package-dependency';
import { CiVulnerability } from '../models/ci-vulnerability';
export interface UploadCiDependencyRequest {
  packageDependencies?: Array<CiPackageDependency> | null;
  packages?: Array<CiPackage> | null;
  scanId: string;
  vulnerabilities?: Array<CiVulnerability> | null;
}
