/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserSummary } from '../models/user-summary';
export interface UserSummaryPage {
  count?: number;
  currentPage?: number;
  items?: Array<UserSummary> | null;
  pageCount?: number;
  size?: number;
}
