/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfile {
  avatar?: string | null;
  email?: string | null;
  fullName?: string | null;
  userId?: string;
  userName?: string | null;
}
