/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDetail } from '../models/user-detail';
export interface UserDetailPage {
  count?: number;
  currentPage?: number;
  items?: Array<UserDetail> | null;
  pageCount?: number;
  size?: number;
}
