/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDetailPage } from '../../models/user-detail-page';
import { UserFilter } from '../../models/user-filter';

export interface GetUserDetailByFilter$Params {
      body?: UserFilter
}

export function getUserDetailByFilter(http: HttpClient, rootUrl: string, params?: GetUserDetailByFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDetailPage>> {
  const rb = new RequestBuilder(rootUrl, getUserDetailByFilter.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDetailPage>;
    })
  );
}

getUserDetailByFilter.PATH = '/api/user/filter';
