/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindingActivity } from '../../models/finding-activity';
import { FindingCommentRequest } from '../../models/finding-comment-request';

export interface AddComment$Params {
  findingId: string;
      body?: FindingCommentRequest
}

export function addComment(http: HttpClient, rootUrl: string, params: AddComment$Params, context?: HttpContext): Observable<StrictHttpResponse<FindingActivity>> {
  const rb = new RequestBuilder(rootUrl, addComment.PATH, 'post');
  if (params) {
    rb.path('findingId', params.findingId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FindingActivity>;
    })
  );
}

addComment.PATH = '/api/finding/{findingId}/comment';
