/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindingDetail } from '../../models/finding-detail';

export interface GetFindingById$Params {
  findingId: string;
}

export function getFindingById(http: HttpClient, rootUrl: string, params: GetFindingById$Params, context?: HttpContext): Observable<StrictHttpResponse<FindingDetail>> {
  const rb = new RequestBuilder(rootUrl, getFindingById.PATH, 'get');
  if (params) {
    rb.path('findingId', params.findingId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FindingDetail>;
    })
  );
}

getFindingById.PATH = '/api/finding/{findingId}';
