/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FindingDetail } from '../../models/finding-detail';
import { UpdateFindingRequest } from '../../models/update-finding-request';

export interface UpdateFinding$Params {
  findingId: string;
      body?: UpdateFindingRequest
}

export function updateFinding(http: HttpClient, rootUrl: string, params: UpdateFinding$Params, context?: HttpContext): Observable<StrictHttpResponse<FindingDetail>> {
  const rb = new RequestBuilder(rootUrl, updateFinding.PATH, 'patch');
  if (params) {
    rb.path('findingId', params.findingId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FindingDetail>;
    })
  );
}

updateFinding.PATH = '/api/finding/{findingId}';
