/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tickets } from '../../models/tickets';
import { TicketType } from '../../models/ticket-type';

export interface CreateProjectPackageTicket$Params {
  projectId: string;
  packageId: string;
  ticketType?: TicketType;
}

export function createProjectPackageTicket(http: HttpClient, rootUrl: string, params: CreateProjectPackageTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<Tickets>> {
  const rb = new RequestBuilder(rootUrl, createProjectPackageTicket.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.path('packageId', params.packageId, {"style":"simple"});
    rb.query('ticketType', params.ticketType, {"style":"form"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tickets>;
    })
  );
}

createProjectPackageTicket.PATH = '/api/project/{projectId}/package/{packageId}/ticket';
