/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectScanFilter } from '../../models/project-scan-filter';
import { ProjectScanPage } from '../../models/project-scan-page';

export interface GetProjectScans$Params {
  projectId: string;
      body?: ProjectScanFilter
}

export function getProjectScans(http: HttpClient, rootUrl: string, params: GetProjectScans$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectScanPage>> {
  const rb = new RequestBuilder(rootUrl, getProjectScans.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectScanPage>;
    })
  );
}

getProjectScans.PATH = '/api/project/{projectId}/scan/filter';
