/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThresholdProject } from '../../models/threshold-project';

export interface GetThresholdProject$Params {
  projectId: string;
}

export function getThresholdProject(http: HttpClient, rootUrl: string, params: GetThresholdProject$Params, context?: HttpContext): Observable<StrictHttpResponse<ThresholdProject>> {
  const rb = new RequestBuilder(rootUrl, getThresholdProject.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThresholdProject>;
    })
  );
}

getThresholdProject.PATH = '/api/project/{projectId}/threshold';
