/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectFilter } from '../../models/project-filter';
import { ProjectSummaryPage } from '../../models/project-summary-page';

export interface GetProjectByFilter$Params {
      body?: ProjectFilter
}

export function getProjectByFilter(http: HttpClient, rootUrl: string, params?: GetProjectByFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectSummaryPage>> {
  const rb = new RequestBuilder(rootUrl, getProjectByFilter.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectSummaryPage>;
    })
  );
}

getProjectByFilter.PATH = '/api/project/filter';
