/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectInfo } from '../../models/project-info';

export interface GetProjectInfo$Params {
  projectId: string;
}

export function getProjectInfo(http: HttpClient, rootUrl: string, params: GetProjectInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectInfo>> {
  const rb = new RequestBuilder(rootUrl, getProjectInfo.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectInfo>;
    })
  );
}

getProjectInfo.PATH = '/api/project/{projectId}';
