/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectCommitFilter } from '../../models/project-commit-filter';
import { ProjectCommitScanSummaryPage } from '../../models/project-commit-scan-summary-page';

export interface GetProjectCommitScanSummary$Params {
  projectId: string;
      body?: ProjectCommitFilter
}

export function getProjectCommitScanSummary(http: HttpClient, rootUrl: string, params: GetProjectCommitScanSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectCommitScanSummaryPage>> {
  const rb = new RequestBuilder(rootUrl, getProjectCommitScanSummary.PATH, 'post');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectCommitScanSummaryPage>;
    })
  );
}

getProjectCommitScanSummary.PATH = '/api/project/{projectId}/commit/filter';
