/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { JiraProject } from '../../models/jira-project';

export interface ListJiraProjects$Params {
  projectId: string;
  reload?: boolean;
}

export function listJiraProjects(http: HttpClient, rootUrl: string, params: ListJiraProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<JiraProject>>> {
  const rb = new RequestBuilder(rootUrl, listJiraProjects.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.query('reload', params.reload, {"style":"form"});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<JiraProject>>;
    })
  );
}

listJiraProjects.PATH = '/api/project/{projectId}/integration/jira/projects';
