/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectMember } from '../../models/project-member';
import { UpdateProjectMemberRequest } from '../../models/update-project-member-request';

export interface UpdateProjectMember$Params {
  projectId: string;
  userId: string;
      body?: UpdateProjectMemberRequest
}

export function updateProjectMember(http: HttpClient, rootUrl: string, params: UpdateProjectMember$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectMember>> {
  const rb = new RequestBuilder(rootUrl, updateProjectMember.PATH, 'patch');
  if (params) {
    rb.path('projectId', params.projectId, {"style":"simple"});
    rb.path('userId', params.userId, {"style":"simple"});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectMember>;
    })
  );
}

updateProjectMember.PATH = '/api/project/{projectId}/member/{userId}';
