pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'io.quarkus' version '3.17.5'
    }
}

rootProject.name = 'warden-scanners'

include 'warden-client'
include 'scanner-gitleaks'
include 'scanner-semgrep'
include 'scanner-trufflehog'
include 'scanner-trivy-iac'
include 'scanner-trivy'
include 'scanner-grype'
include 'scanner-trivy-image'
include 'scanner-zap'
include 'scanner-nuclei'
include 'scanner-osv'
include 'scanner-syft'
include 'scanner-checkov'
include 'scanner-guarddog'
include 'scanner-deepsec'
