<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <RootNamespace>Warden</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RazorLangVersion>latest</RazorLangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aguacongas.AspNetCore.Authentication" Version="6.1.0" />
        <PackageReference Include="Aguacongas.AspNetCore.Authentication.EntityFramework" Version="6.1.0" />
        <PackageReference Include="Atlassian.SDK" Version="13.0.0" />
        <PackageReference Include="ClosedXML" Version="0.104.2" />
        <PackageReference Include="FluentResults" Version="3.16.0" />
        <PackageReference Include="MailKit" Version="4.11.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.8"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2"/>
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
        <PackageReference Include="QuestPDF" Version="2025.1.2" />
        <PackageReference Include="QuestPDF.Markdown" Version="1.31.1" />
        <PackageReference Include="redmine-api" Version="4.7.1" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
        <PackageReference Include="ScottPlot" Version="5.0.54" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.116.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1"/>
    </ItemGroup>
    <ItemGroup>
        <None Update="Resources\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>
    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\RenderMessage.razor" />
    </ItemGroup>

</Project>
