/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScaStatistic } from '../../models/sca-statistic';
import { StatisticFilter } from '../../models/statistic-filter';

export interface ScaStatistic$Params {
      body?: StatisticFilter
}

export function scaStatistic(http: HttpClient, rootUrl: string, params?: ScaStatistic$Params, context?: HttpContext): Observable<StrictHttpResponse<ScaStatistic>> {
  const rb = new RequestBuilder(rootUrl, scaStatistic.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScaStatistic>;
    })
  );
}

scaStatistic.PATH = '/api/dashboard/sca';
