/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SmtpSetting } from '../../models/smtp-setting';

export interface GetSmtpSetting$Params {
}

export function getSmtpSetting(http: HttpClient, rootUrl: string, params?: GetSmtpSetting$Params, context?: HttpContext): Observable<StrictHttpResponse<SmtpSetting>> {
  const rb = new RequestBuilder(rootUrl, getSmtpSetting.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SmtpSetting>;
    })
  );
}

getSmtpSetting.PATH = '/api/setting/smtp';
